# -*- coding: utf-8 -*-
"""datetime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GjfAwaamEZcaxcw8PScCjuPDojKAPIVu
"""

from datetime import datetime
import pytz

IST = pytz.timezone('Asia/Kolkata')
  
print("IST in Default Format : ", 
      datetime.now(IST))
  
datetime_ist = datetime.now(IST)
print("Date & Time in IST : ", 
      datetime_ist.strftime('%Y:%m:%d %H:%M:%S %Z %z'))

